name: ServerChan
author: Li Keqing<me@kaze.ai>
version: 1.0
api-version: 1.17
main: ai.kaze.ServerChan.ServerChanPlugin
commands:
  bind:
    description: 绑定QQ号
    usage: /<command> [QQ号|cancel]
  unbind:
    description: 解绑QQ号
    usage: /<command>
  forceunbind:
    description: 强制解除绑定QQ号
    usage: /<command> 玩家名|QQ号
  qqsay:
    description: 发送消息到QQ群
    usage: /<command> 消息
